```{r}
library(data.table)
library(tidyverse)
```

```{r}
df <- fread('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')
View(df)
```
early vs mid career pay correlation
```{r}
# strong correlation
df |>
    select(early_career_pay, mid_career_pay) |>
    ggplot(aes(early_career_pay, mid_career_pay)) +
    geom_point() +
    geom_smooth(method = lm)

```


```{r}
df |>
    na.omit() |>
    select(-rank) |>
    arrange(desc(stem_percent)) |>
    slice(1:100) |>
    ggplot(aes(stem_percent, mid_career_pay)) +
    geom_point()+
    geom_smooth(method = 'lm', se=TRUE)
```

```{r}
df |>
    na.omit() |>
    select(make_world_better_percent, stem_percent) |>
    arrange(desc(stem_percent)) |>
    slice(1:100) |>
    ggplot(aes(stem_percent, make_world_better_percent)) +
    geom_point()+
    geom_smooth(method = 'lm', se=TRUE)
```

```{r}
df |>
    na.omit() |>
    group_by(state_name) |>
    summarise(count = n()) |>
    arrange(desc(count)) 
```

```{r}
# colleges and their tuition and stuff 
df <- fread('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')
View(df)
```

# Business Question

```{r}
glimpse(df)
```

Average cost between 2 and 4 year
```{r}
df %>%
    group_by(degree_length) |>
    summarise(count = n()) |>
    slice(1:2) |>
    ggplot(aes(degree_length, count)) +
    geom_col()
```


Cheapest in-state total
```{r}
df |>
    filter(type == 'Public') |>
    filter(degree_length == '4 Year') |>
    group_by(state_code) |>
    summarise(average_cost_of_attendance = mean(in_state_total)) |>
    arrange(average_cost_of_attendance) |>
    slice(2:11) |>
    arrange(average_cost_of_attendance) |>
    ggplot(aes(state_code, average_cost_of_attendance)) +
    geom_col() + 
    coord_flip()
```

Cheapest out-of-state total
```{r}
df |>
    filter(type == 'Public') |>
    filter(degree_length == '4 Year') |>
    group_by(state_code) |>
    summarise(average_cost_of_attendance = mean(out_of_state_total)) |>
    arrange(average_cost_of_attendance) |>
    slice(2:11) |>
    arrange(average_cost_of_attendance) |>
    ggplot(aes(state_code, average_cost_of_attendance)) +
    geom_col() + 
    coord_flip()
```


Cheapest and most expensive state
```{r}

```


Private vs Public average cost

```{r}
df |>
    filter(degree_length == "4 Year") |>
    group_by(type) |>
    summarise(average = mean(in_state_total)) |>
    ggplot(aes(type, average)) +
    geom_col() +
    coord_flip()
```

```{r}
df <- fread("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv")
View(df)
```

```{r}
df |>
    na.omit() |>
    select(name, total_enrollment, state) |>
    distinct() |>
    group_by(state) |>
    summarize(state_total = sum(total_enrollment)) |>
    distinct() |>
    arrange(desc(state_total))
```
```{r}
df <- fread("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/all-schools.csv")
df
```

```{r}
df <- fread("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/student_diversity.csv")
View(df)
```
```{r}
df <- fread("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv")
View(df)
```

### Distribution of income levels of students
```{r}
df |>
    
```

